[workspace]

members = [
    "krusty",
    "rusty-xv6",
    "shared"
]

[workspace.dependencies]
linked_list_allocator = "0.10.5"
lazy_static = {version = "1.4.0", features = ["spin_no_std"] }
log = "0.4.20"
ansi_rgb = "0.2.0"
